name: language_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.0.0
  share_plus: ^7.0.0
  clipboard: ^0.1.3
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.0
  cupertino_icons: ^1.0.8
  audioplayers: ^6.4.0
  http: ^1.3.0
  image_picker: ^1.1.2
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^17.2.2
  fl_chart: ^0.68.0  # Package để vẽ biểu đồ
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  intl: ^0.19.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/res/imagesLA/
  fonts:
    - family: BeVietnamPro
      fonts:
        - asset: assets/fonts/BeVietnamPro/BeVietnamPro-Regular.ttf
        - asset: assets/fonts/BeVietnamPro/BeVietnamPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/BeVietnamPro/BeVietnamPro-Italic.ttf
          style: italic

# Phần l10n phải nằm ở cấp gốc, không nằm trong flutter:
l10n:
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
  output-dir: lib/l10n
  